#!/usr/bin/perl

use strict;
use warnings;
use Scalar::Util qw(looks_like_number);

my $tol = 1e-16;

sub numeric_equals{
	my ($v1, $v2) = @_;
	if (!looks_like_number($v1) || !looks_like_number($v2)) {
		die "Non-numeric field encountered: '$v1' or '$v2'\n";
	}
	if ($v1 =~ /nan|inf/i || $v2 =~ /nan|inf/i) {
		return 0; # Reject NaN/Inf
	}
	return abs($v1-$v2) < $tol;
}

if($#ARGV < 1){ exit 1; }

my $file1 = $ARGV[0];
my $file2 = $ARGV[1];
if($#ARGV > 1){ $tol = $ARGV[2]; }

open(my $FP1, "<", $file1) or die "Cannot open $file1: $!\n";
open(my $FP2, "<", $file2) or die "Cannot open $file2: $!\n";

my $lineno1 = 0;
my $lineno2 = 0;
my $has_diff = 0;

sub get_next_line {
	my ($fh, $lineno_ref) = @_;
	while(my $line = <$fh>) {
		$$lineno_ref++;
		return $line unless $line =~ /^\s*#/;
	}
	return undef;
}

while(my $line1 = get_next_line($FP1, \$lineno1)) {
	my $line2 = get_next_line($FP2, \$lineno2);
	if (!defined $line2) {
		print "Different number of lines: $file1 has more lines than $file2.\n";
		$has_diff = 1;
		last;
	}
	chomp($line1);
	chomp($line2);
	# Split on whitespace, skipping empty elements
	my @a1 = split ' ', $line1;
	my @a2 = split ' ', $line2;
	if($#a1 != $#a2){
		print("Different number of values at $file1:$lineno1 ($file2:$lineno2).\n");
		$has_diff = 1;
	}else{
		for(my $i=0; $i <= $#a1; ++$i){
			if(!numeric_equals($a1[$i], $a2[$i])){
				my $ip1 = $i+1;
				print("$file1:$lineno1 ($file2:$lineno2): $a1[$i] != $a2[$i] (tol $tol).\n");
				$has_diff = 1;
			}
		}
	}
}

if (defined(get_next_line($FP2, \$lineno2))) {
	print "Different number of lines: $file2 has more lines than $file1.\n";
	$has_diff = 1;
}

close($FP1);
close($FP2);

exit($has_diff);
